--- #YAML:1.0
# cherryEPG configuration file
appname: "cherryWeb"
description: "Demo Installation"
layout: "system"
charset: "UTF-8"
template: "template_toolkit"
session: "YAML"
startup_info: 1
show_errors: 0
# common
engines:
  session:
    YAML:
      cookie_name: cherry.session
      cookie_duration: '24 hours'
      cookie_same_site: Lax
      is_http_only: 1
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag: '%>'
      encoding: 'utf8'
  logger:
    console:
      log_level: error
plugins:
  Ajax:
    content_type: 'application/json'
  Auth::Extensible:
    login_without_redirect: 1
    no_login_handler: 1
    login_page_handler: 'cherryWeb::loginPageHandler'
    permission_denied_page_handler: 'cherryWeb::permissionDeniedPageHandler'
    realms:
      config_unix:
        provider: Unix  # roles are system groups
core:
  basedir: /var/lib/cherryepg/
  datasource: dbi:mysql:dbname=cherry_db;host=localhost
  user: cherryepg
  pass: visnja
  lang: en
  exportIP: 127.10.10.9
  parallelTasks: 16    # number of parallel tasks when grabbing/ingesting and building
  taster:
    webgrab:
    eventbudget:
      days: 7
      threshold:
        warning: 3
        critical: 2
log4perl:  |-
  log4perl.logger                    = ${LOGLEVEL}, Screen, Dbs
  log4perl.oneMessagePerAppender     = 1
  log4perl.appender.Screen              = cherryEpg::Log4perlMyScreen
  log4perl.appender.Screen.stderr       = 0
  log4perl.appender.Screen.layout       = NoopLayout
  log4perl.appender.Screen.warp_message = 0
  log4perl.appender.Dbs                 = cherryEpg::Log4perlMyDBI
  log4perl.appender.Dbs.Threshold       = INFO
  log4perl.appender.Dbs.datasource      = $datasource
  log4perl.appender.Dbs.username        = $user
  log4perl.appender.Dbs.password        = $pass
  log4perl.appender.Dbs.sql             = INSERT INTO log (level, category, text, channel_id, eit_id, info) VALUES( ?, ?, ?, ?, ?, ?);
  log4perl.appender.Dbs.params.1        = %p
  log4perl.appender.Dbs.params.2        = %c
  log4perl.appender.Dbs.usePreparedStmt = 1
  log4perl.appender.Dbs.layout          = Log::Log4perl::Layout::NoopLayout
  log4perl.appender.Dbs.warp_message    = sub { my ( $text, $channel, $eit, $info) = @_; return ( $text, $channel || undef, $eit || undef, defined $info ? JSON::XS::encode_json( $info) : undef);}
  log4perl.appender.Mail              = cherryEpg::Log4perlMail
  log4perl.appender.Mail.Threshold    = WARN
  log4perl.appender.Mail.layout       = Log::Log4perl::Layout::NoopLayout
  log4perl.appender.Mail.Host         = smtp.gmail.com:587
  log4perl.appender.Mail.auth         = username:password
  log4perl.appender.Mail.doSSL        = starttls,
  log4perl.appender.Mail.to           = recipient_mail@mail.com
  log4perl.appender.Mail.from         = Watchdog <sender_mail@gmail.com>
  log4perl.appender.Mail.Debug        = 0
  log4perl.appender.Mail.warp_message = 0
  log4perl.appender.Graylog              = cherryEpg::Log4perlGraylog
  log4perl.appender.Graylog.PeerAddr     = localhost
  log4perl.appender.Graylog.PeerPort     = 12201
  log4perl.appender.Graylog.layout       = NoopLayout
  log4perl.appender.Graylog.warp_message = 0
